### ISSUE TITLE
TODO: Complete the WriteMaster/Ordinary Functions 

### ISSUE THREAD

**Issue by KASPAROV84** [KASPAROV84/From_Scratchv1#1]
The Function,when called should write the UID of the scanned Tag to Master/Ordinary file in SD Card

**Comment by TheBeachMaster** [comment]
Seen

**Comment by KASPAROV84** [comment]
Got the code to write data in these files but for some reason it is writing 4 (0) rather than the UID. I'll figure it out but for now at least we're posting data to file.

**Comment by KASPAROV84** [comment]
Fixed the code. The UID's are now being written to Master and Ordinary .txt files.
