### ISSUE TITLE
TODO: Hook up "grep" Function to the rest of the code.

### ISSUE THREAD

**Issue by KASPAROV84** [KASPAROV84/From_Scratchv1#2]
We shall have 2 applications of this function:

1. Search for a Match in the Master File and direct control to Programming or Normal Mode
2. Search the Ordinary File to direct control to either grant or deny access

**Comment by TheBeachMaster** [comment]
Awaiting Test

**Comment by KASPAROV84** [comment]
There appears to be a conflict between master and branch. I was not able to pull your branch to test. Will have to sort out the conflict to enable merge of local file and remote master.

**Comment by TheBeachMaster** [comment]
Working
