### ISSUE TITLE
TODO: LCD Hook up

### ISSUE THREAD

**Issue by KASPAROV84** [KASPAROV84/From_Scratchv1#3]
Hook up a 1604 LCD in the code and write necessary Prompts and feedback in the LCD
NB: The serial.print code shall be used for debugging hence we shall still retain it.
NB: The LCD Prompts need not be as wordy as the serial.print feedback.

**Comment by TheBeachMaster** [comment]
LCD Library seems to have issues on my side.I'll definitely look into it

**Comment by KASPAROV84** [comment]
You may need to download my version of LCD library. Remind me to send you the author.
I have hooked up the LCD and printed some initial messages to LCD. I'm using a 16 x 4.
