### ISSUE TITLE
TODO: GrepMaster Coding 

### ISSUE THREAD

**Issue by KASPAROV84** [KASPAROV84/From_Scratchv1#6]
Study EEPROM example and;

 1. List Methods
2. Summary of each method's function 
3. Assess each methods relevance to our SD functionality
4. List out methods that can be reused as they are.
5. Code replacement methods for the ones that cannot be reused
6. Test out final code and optimize

**Comment by TheBeachMaster** [comment]
This issue has been resolved so far
